In [1]:
import pandas as pd

In [2]:
df = pd.read_parquet("../data/brunch/session.parquet")

In [3]:
import json
from tqdm import tqdm

with open("../data/dictionary.json") as fp:
    dictionary = json.load(fp)
    
def make_label(x):
    session = x["history"]
    session = [dictionary[elem] for elem in session if elem in dictionary]
    x["session"] = session
    return x

tqdm.pandas()
df = df.progress_apply(make_label, axis=1)

In [ ]:
def make_mask(x):
    session_length = len(x["session"])
    # generating session mask
    session_mask = [1.0] * (session_length - 1)
    session_mask = [0.0] + session_mask
    # generating user mask
    user_mask = [0.0] * (session_length - 1)
    user_mask = user_mask + [1.0]
    x["session_mask"] = session_mask
    x["user_mask"] = user_mask
    return x

df = df.progress_apply(make_mask, axis=1)

In [5]:
#000127ad0f1981cae1292efdb228f0e9
df_train = pd.read_parquet("../data/train.parquet")

Empty DataFrame
Columns: [id, history, timestamp, session, session_mask, user_mask]
Index: []

In [16]:
sample = df_train[df_train.id == "#000549d84169355d490b029755f99381"]

In [17]:
session_mask = sample["session_mask"].values

In [18]:
session_mask

array([array([0.]), array([0.]), array([0., 1.]), array([0.]),
       array([0.]), array([0., 1., 1., 1., 1.]), array([0.]), array([0.]),
       array([0.]), array([0., 1., 1.]), array([0.]), array([0.]),
       array([0., 1., 1., 1., 1., 1., 1., 1., 1.])], dtype=object)

In [15]:
import numpy as np

elements = [elem for elem in session_mask]
array = np.concatenate(elements, axis=None)
array

array([0., 1., 1., 1., 1., 1., 1., 0., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       0., 1., 1., 1., 1., 1., 0., 1., 1., 1.])

In [19]:
sample

,id,history,timestamp,session,session_mask,user_mask
2043951,#000549d84169355d490b029755f99381,[@cherry3333_1],2019-01-03 11:00:00,[134697],[0.0],[1.0]
2072078,#000549d84169355d490b029755f99381,[@cherry3333_2],2019-01-04 12:00:00,[430286],[0.0],[1.0]
2121999,#000549d84169355d490b029755f99381,"[@nareun_134, @cherry3333_2, @cherry3333_1]",2019-01-06 16:00:00,"[430286, 134697]","[0.0, 1.0]","[0.0, 1.0]"
2131113,#000549d84169355d490b029755f99381,[@cherry3333_3],2019-01-06 23:00:00,[206046],[0.0],[1.0]
2148534,#000549d84169355d490b029755f99381,[@cherry3333_4],2019-01-07 16:00:00,[594840],[0.0],[1.0]
2199073,#000549d84169355d490b029755f99381,"[@cherry3333_4, @cherry3333_3, @cherry3333_2, ...",2019-01-09 15:00:00,"[594840, 206046, 430286, 134697, 594840]","[0.0, 1.0, 1.0, 1.0, 1.0]","[0.0, 0.0, 0.0, 0.0, 1.0]"
2206399,#000549d84169355d490b029755f99381,[@cherry3333_5],2019-01-09 21:00:00,[134516],[0.0],[1.0]
2290100,#000549d84169355d490b029755f99381,[@cherry3333_6],2019-01-13 11:00:00,[375092],[0.0],[1.0]
2338774,#000549d84169355d490b029755f99381,[@cherry3333_7],2019-01-15 01:00:00,[14087],[0.0],[1.0]
2479535,#000549d84169355d490b029755f99381,"[@cherry3333_7, @cherry3333_5, @cherry3333_6]",2019-01-20 16:00:00,"[14087, 134516, 375092]","[0.0, 1.0, 1.0]","[0.0, 0.0, 1.0]"
2534920,#000549d84169355d490b029755f99381,[@brunch_148],2019-01-22 18:00:00,[539383],[0.0],[1.0]
2565626,#000549d84169355d490b029755f99381,[@brunch_149],2019-01-23 20:00:00,[420070],[0.0],[1.0]
3241417,#000549d84169355d490b029755f99381,"[@cherry3333_8, @cherry3333_7, @cherry3333_6, ...",2019-02-19 05:00:00,"[122657, 14087, 375092, 14087, 122657, 206046,...","[0.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0, 1.0]","[0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1.0]"